version: '3'
services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    restart: always
    build:
      context: ./postgres/
      dockerfile: Dockerfile
  backend.authorization:
    image: backend.authorization
    container_name: backend.authorization
    ports:
      - 8080:8080
#        environment:
#          PG_LOGIN: postgres
#          PG_PASSWORD: postgres
#          PG_DB_NAME: postgres
#          PG_HOST: db
    restart: always
    build:
      context: ./backend.authorization/
      dockerfile: Dockerfile
    depends_on:
      - db